export const FETCH_EVENT_REQUEST = "FETCH_EVENT_REQUEST";
export const FETCH_EVENT_SUCCESS = "FETCH_EVENT_SUCCESS";
export const FETCH_EVENT_FAILED = "FETCH_EVENT_FAILED";

export const SEARCH_EVENT_REQUEST = "SEARCH_EVENT_REQUEST";
export const SEARCH_EVENT_SUCCESS = "SEARCH_EVENT_SUCCESS";
export const SEARCH_EVENT_FAILED = "SEARCH_EVENT_FAILED";

export const FILTER_TYPE = "FILTER_TYPE";
export const FILTER_TYPE_FAILURE = "FILTER_TYPE_FAILURE";

export const FILTER_DATE = "FILTER_DATE";
export const FILTER_DATE_FAILURE = "FILTER_DATE_FAILURE";

export const FILTER_EVENTS = "FILTER_EVENTS";
export const FILTER_EVENTS_FAILURE = "FILTER_EVENTS_FAILURE";
 
export const CREATE_EVENT = "CREATE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const GET_EVENTS = "GET_EVENTS";
export const GET_ALL_EVENTS = "GET_ALL_EVENTS";

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
